# Generated by Django 4.0.6 on 2022-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_salesorder_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='file_share',
            field=models.FileField(default=1, upload_to='estimate'),
            preserve_default=False,
        ),
    ]
