# Generated by Django 4.1 on 2022-10-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_estimate_file_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Invoiced', 'Invoiced')], default='Draft', max_length=150),
        ),
    ]
