# Generated by Django 4.0.6 on 2022-10-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_payment_amtapply_remove_payment_amtcredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amtapply',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='amtcredit',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
