# Generated by Django 4.1 on 2022-10-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_salesorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='reason',
            fields=[
                ('reasonid', models.AutoField(primary_key=True, serialize=False, verbose_name='REASONID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
