# Generated by Django 4.1 on 2022-10-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_reason'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reason',
            new_name='stockreason',
        ),
    ]
