# Generated by Django 4.0.6 on 2022-10-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_payment_amtapply_payment_amtcredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='referno',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
