# Generated by Django 4.1 on 2022-10-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_stockadjust'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjust',
            name='item2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='item3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='item4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='item5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='new_qty2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='new_qty3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='new_qty4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='new_qty5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty_hand2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty_hand3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty_hand4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='qty_hand5',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockadjust',
            name='status',
            field=models.CharField(default='DRAFT', max_length=100),
        ),
    ]
