# Generated by Django 4.0.6 on 2022-10-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_payment_findinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentitems',
            name='duedate',
            field=models.DateField(),
        ),
    ]
