# Generated by Django 4.1 on 2022-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_stockadjust_item2_stockadjust_item3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='purchase_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
