# Generated by Django 4.0.6 on 2022-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_payment_referno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitems',
            name='duedate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
