# Generated by Django 4.0.6 on 2022-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_paymentitems_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
