# Generated by Django 4.1 on 2022-10-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_itemtable_purchase_cost_alter_itemtable_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='purchase_cost',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(default=''),
        ),
    ]
