# Generated by Django 4.1 on 2022-10-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_itemtable_purchase_cost_alter_itemtable_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='inventry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
