# Generated by Django 4.0.6 on 2022-10-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_customer_opening_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='baldue',
            field=models.CharField(max_length=100),
        ),
    ]
