# Generated by Django 4.0.6 on 2022-10-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_invoice_baldue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='baldue',
            field=models.FloatField(),
        ),
    ]
