# Generated by Django 4.0.6 on 2022-10-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_invoice_baldue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amtcredit',
            field=models.FloatField(),
        ),
    ]
