# Generated by Django 4.0.6 on 2022-10-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_invoice_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amtreceived',
            field=models.FloatField(),
        ),
    ]
