# Generated by Django 4.0.6 on 2022-10-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_payment_amtreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentitems',
            name='balamount',
            field=models.FloatField(),
        ),
    ]
