# Generated by Django 4.0.6 on 2022-10-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_payment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='balance',
        ),
    ]
