# Generated by Django 4.0.6 on 2022-10-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_payment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
