# Generated by Django 4.0.6 on 2022-10-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amtapply',
            field=models.FloatField(),
        ),
    ]
