# Generated by Django 4.0.6 on 2022-10-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_cust_statment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_statment',
            old_name='invoice',
            new_name='inv',
        ),
        migrations.RenameField(
            model_name='cust_statment',
            old_name='payment',
            new_name='pay',
        ),
    ]
