# Generated by Django 4.0.6 on 2022-10-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_invoice_cust_statment_inv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_statment',
            name='inv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
    ]
