# Generated by Django 4.0.6 on 2022-10-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_cust_statment_inv_alter_cust_statment_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_statment',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payment'),
        ),
    ]
