# Generated by Django 4.0.6 on 2022-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_cust_statment_inv_alter_cust_statment_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_statment',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Payments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Transactions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
