# Generated by Django 4.0.6 on 2022-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_cust_statment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_statment',
            name='Details2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
