# Generated by Django 4.1 on 2022-10-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_itemtable_inventry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='etransporter',
            fields=[
                ('etransporterid', models.AutoField(primary_key=True, serialize=False, verbose_name='ETRANSPORTERID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tid', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
