# Generated by Django 4.0.6 on 2022-10-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_cust_statment_details2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_statment',
            name='Amount',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Payments',
            field=models.FloatField(default='', null=True),
        ),
    ]
