# Generated by Django 4.0.6 on 2022-10-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_cust_statment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
