# Generated by Django 4.1 on 2022-10-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_etransporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ewayinv',
            fields=[
                ('ewayinvid', models.AutoField(primary_key=True, serialize=False, verbose_name='EWAYINV')),
                ('transaction_stype', models.CharField(blank=True, default='', max_length=255)),
                ('transporter', models.CharField(blank=True, default='', max_length=255)),
                ('distance', models.CharField(blank=True, default='', max_length=255)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=255)),
                ('transport_doc_no', models.CharField(blank=True, default='', max_length=255)),
                ('transport_doc_date', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
