# Generated by Django 4.0.6 on 2022-10-19 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_customer_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_statment',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
            preserve_default=False,
        ),
    ]
