# Generated by Django 4.0.6 on 2022-10-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_cust_statment_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cust_statment',
            name='Payments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.FloatField(null=True),
        ),
    ]
