# Generated by Django 4.1 on 2022-10-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_customer_date_alter_cust_statment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='inventry',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='purchase_cost',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='stock',
            field=models.IntegerField(default=''),
        ),
        migrations.CreateModel(
            name='stockreason',
            fields=[
                ('reasonid', models.AutoField(primary_key=True, serialize=False, verbose_name='REASONID')),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='stockadjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='', max_length=100)),
                ('ref_no', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('attach', models.FileField(default='', upload_to='')),
                ('status', models.CharField(default='DRAFT', max_length=100)),
                ('item1', models.CharField(max_length=100, null=True)),
                ('qty1', models.CharField(max_length=100, null=True)),
                ('qty_hand1', models.CharField(default='', max_length=100)),
                ('new_qty1', models.CharField(default='', max_length=100)),
                ('item2', models.CharField(max_length=100, null=True)),
                ('qty2', models.CharField(max_length=100, null=True)),
                ('qty_hand2', models.CharField(default='', max_length=100)),
                ('new_qty2', models.CharField(default='', max_length=100)),
                ('item3', models.CharField(max_length=100, null=True)),
                ('qty3', models.CharField(max_length=100, null=True)),
                ('qty_hand3', models.CharField(default='', max_length=100)),
                ('new_qty3', models.CharField(default='', max_length=100)),
                ('item4', models.CharField(max_length=100, null=True)),
                ('qty4', models.CharField(max_length=100, null=True)),
                ('qty_hand4', models.CharField(default='', max_length=100)),
                ('new_qty4', models.CharField(default='', max_length=100)),
                ('item5', models.CharField(max_length=100, null=True)),
                ('qty5', models.CharField(max_length=100, null=True)),
                ('qty_hand5', models.CharField(default='', max_length=100)),
                ('new_qty5', models.CharField(default='', max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='ewayinv',
            fields=[
                ('ewayinvid', models.AutoField(primary_key=True, serialize=False, verbose_name='EWAYINV')),
                ('transaction_stype', models.CharField(blank=True, default='', max_length=255)),
                ('transporter', models.CharField(blank=True, default='', max_length=255)),
                ('distance', models.CharField(blank=True, default='', max_length=255)),
                ('transport_mode', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=255)),
                ('transport_doc_no', models.CharField(blank=True, default='', max_length=255)),
                ('transport_doc_date', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.CreateModel(
            name='etransporter',
            fields=[
                ('etransporterid', models.AutoField(primary_key=True, serialize=False, verbose_name='ETRANSPORTERID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tid', models.CharField(blank=True, default='', max_length=255)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
