# Generated by Django 4.1 on 2022-10-30 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_accounts1_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='reconcile',
            fields=[
                ('reconcileid', models.AutoField(primary_key=True, serialize=False, verbose_name='RECONCILEID')),
                ('start_date', models.CharField(blank=True, default='', max_length=255)),
                ('end_date', models.CharField(blank=True, default='', max_length=255)),
                ('closing_balance', models.CharField(blank=True, default='', max_length=255)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.accounts1')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
